### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by FlexibleSwift** [excxpt/destiny-profile-scraper#1]

**Comment by excxpt** [comment]
Hey mate!

This is a work-in-progress project right now and has very limited funtioality. I'm mostly just using GitHub to track my progress as I'm a student developer.

That being said, the tool will be up and running on my personal domain within the next day. I'll report back once it's up 😄

**Comment by excxpt** [comment]
It should be accessible now! Available [here](http://dps.excxpt.xyz).
